### ISSUE TITLE
Upgrade to axios v1+

### ISSUE THREAD

**Issue by segevfiner** [segevfiner/axios-light-my-request-adapter#2]
There are breaking changes and changes in some of the internal code that was copy-pasted/extracted from axios. Will have to go over everything and update.

**Comment by thyming** [comment]
would you accept a PR with this upgrade?

**Comment by segevfiner** [comment]
Not that simple really. It's essentially rewriting this as Axios v1 changed quite thoroughly...

Might even want to rewrite in plain JS and import from axios/unsafe to reduce the duplicated code, and tough work of adding types to untyped code.

So yeah, basically starting over from scratch.

**Comment by segevfiner** [comment]
You can try #7
